source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'RealmMapViewExample' do
  pod 'Realm', :modular_headers => true
  pod 'RealmSwift'
  pod 'RealmSFRestaurantData', ">=0.3", :modular_headers => true
end
