source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'ABFRealmMapViewExample' do
  pod 'RealmSFRestaurantData', ">=0.3"
  pod 'Realm', '~> 3.17.0'

  target 'ABFRealmMapViewExampleTests' do
    inherit! :search_paths
    pod 'Realm/Headers'
  end
end

